export const clubhouseData = [
    {
      id: 1,
      title: 'Luxury Clubhouse',
      price: '$1,500/day',
      location: 'Scenic Location',
      size: 'Large',
      rooms: 5,
      availability: 'available',
      imageUrl: require('../../images/club-house (1).webp'),
      type: 'Clubhouse',
    },
    {
      id: 2,
      title: 'Modern Event Space',
      price: '$1,200/day',
      location: 'City Center',
      size: 'Medium',
      rooms: 3,
      availability: 'available',
      imageUrl: require('../../images/club-house (2).webp'),
      type: 'Clubhouse',
    },
    {
      id: 3,
      title: 'Rustic Retreat Venue',
      price: '$1,800/day',
      location: 'Countryside',
      size: 'Large',
      rooms: 6,
      availability: 'available',
      imageUrl: require('../../images/club-house (3).webp'),
      type: 'Clubhouse',
    },
    {
      id: 4,
      title: 'Exclusive Event Hall',
      price: '$2,000/day',
      location: 'Upscale District',
      size: 'Extra Large',
      rooms: 8,
      availability: 'available',
      imageUrl: require('../../images/club-house (4).webp'),
      type: 'Clubhouse',
    },
  ];
  