export const apartmentData = [
    {
      id: 1,
      title: 'Spacious Family Home',
      price: '$350,000',
      location: 'Suburban Neighborhood',
      size: 'Large',
      rooms: 4,
      availability: 'available',
      imageUrl: require('../../images/house-property (1).webp'),
      type: 'Houses',
    },
    {
      id: 2,
      title: 'Cozy Cottage',
      price: '$150,000',
      location: 'Rural Area',
      size: 'Small',
      rooms: 2,
      availability: 'available',
      imageUrl: require('../../images/house-property (2).webp'),
      type: 'Houses',
    },
    {
      id: 3,
      title: 'Modern Urban Loft',
      price: '$500,000',
      location: 'City Center',
      size: 'Medium',
      rooms: 3,
      availability: 'available',
      imageUrl: require('../../images/house-property (3).webp'),
      type: 'Houses',
    },
    {
      id: 4,
      title: 'Elegant Colonial House',
      price: '$800,000',
      location: 'Historic District',
      size: 'Large',
      rooms: 5,
      availability: 'available',
      imageUrl: require('../../images/house-property (4).webp'),
      type: 'Houses',
    },
    {
      id: 5,
      title: 'Charming Victorian Home',
      price: '$600,000',
      location: 'Victorian Village',
      size: 'Medium',
      rooms: 4,
      availability: 'available',
      imageUrl: require('../../images/house-property (5).webp'),
      type: 'Houses',
    },
    {
      id: 6,
      title: 'Luxurious Beachfront Villa',
      price: '$1,200,000',
      location: 'Beach Resort',
      size: 'Extra Large',
      rooms: 6,
      availability: 'available',
      imageUrl: require('../../images/house-property (6).webp'),
      type: 'Houses',
    },
    {
      id: 7,
      title: 'Mountain View Retreat',
      price: '$900,000',
      location: 'Mountainous Area',
      size: 'Large',
      rooms: 5,
      availability: 'available',
      imageUrl: require('../../images/house-property (7).webp'),
      type: 'Houses',
    },
    {
      id: 8,
      title: 'Contemporary Hillside Home',
      price: '$750,000',
      location: 'Hillside Community',
      size: 'Medium',
      rooms: 4,
      availability: 'available',
      imageUrl: require('../../images/house-property (8).webp'),
      type: 'Houses',
    },
    {
      id: 9,
      title: 'Rustic Countryside Cabin',
      price: '$300,000',
      location: 'Countryside',
      size: 'Small',
      rooms: 4,
      availability: 'available',
      imageUrl: require('../../images/apartment-properties (2).webp'),
      type: 'Houses',
     
    }
]  