export const houseData = [
  {
    id: 1,
    title: '7080 Old Westport Avenue South Ozone Park, NY 11420',
    price: '$100',
    location: 'City A',
    size: 'Medium',
    rooms: 21,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (1).webp'),
    type: 'Apartment',
  },
  {
    id: 2,
    title: '127 West Smoky Hollow St. Staten Island, NY 10314',
    price: '$150',
    location: 'City B',
    size: 'Large',
    rooms: 12,
    availability: 'sold',
    imageUrl: require('../../images/apartment-properties (2).webp'), 
    type: 'Apartment',
  },
  {
    id: 3,
    title: '969 Academy St. South Richmond Hill, NY 11419',
    price: '$80',
    location: 'City C',
    size: 'Small',
    rooms: 8,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (3).webp'), 
    type: 'Apartment',
  },
  {
    id: 4,
    title: '123 Main Street, City D',
    price: '$120',
    location: 'City D',
    size: 'Large',
    rooms: 15,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (4).webp'), 
    type: 'Apartment',
  },
  {
    id: 5,
    title: '456 Elm Avenue, City E',
    price: '$90',
    location: 'City E',
    size: 'Medium',
    rooms: 10,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (5).webp'), 
    type: 'Apartment',
  },
  {
    id: 6,
    title: '789 Oak Boulevard, City F',
    price: '$110',
    location: 'City F',
    size: 'Small',
    rooms: 7,
    availability: 'sold',
    imageUrl: require('../../images/apartment-properties (6).webp'), 
    type: 'Apartment',
  },
  {
    id: 7,
    title: '321 Pine Street, City G',
    price: '$130',
    location: 'City G',
    size: 'Large',
    rooms: 18,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (7).webp'), 
    type: 'Apartment',
  },
  {
    id: 8,
    title: '654 Cedar Lane, City H',
    price: '$95',
    location: 'City H',
    size: 'Medium',
    rooms: 12,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (8).webp'),
    type: 'Apartment', 
  },
  {
    id: 9,
    title: '987 Maple Drive, City I',
    price: '$85',
    location: 'City I',
    size: 'Small',
    rooms: 9,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (9).webp'),
    type: 'Apartment',
  },
  {
    id: 10,
    title: '246 Birch Court, City J',
    price: '$115',
    location: 'City J',
    size: 'Large',
    rooms: 14,
    availability: 'sold',
    imageUrl: require('../../images/apartment-properties (10).webp'),
    type: 'Apartment',
  },
  {
    id: 11,
    title: '753 Willow Place, City K',
    price: '$105',
    location: 'City K',
    size: 'Medium',
    rooms: 11,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (11).webp'),
    type: 'Apartment',
  },
  {
    id: 12,
    title: '159 Redwood Street, City L',
    price: '$140',
    location: 'City L',
    size: 'Small',
    rooms: 8,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (12).webp'),
    type: 'Apartment',
  },
  {
    id: 13,
    title: '369 Sycamore Lane, City M',
    price: '$75',
    location: 'City M',
    size: 'Large',
    rooms: 20,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (13).webp'),
    type: 'Apartment',
  },
  {
    id: 14,
    title: '852 Olive Avenue, City N',
    price: '$125',
    location: 'City N',
    size: 'Medium',
    rooms: 13,
    availability: 'sold',
    imageUrl: require('../../images/apartment-properties (14).webp'),
    type: 'Apartment',
  },
  {
    id: 15,
    title: '147 Juniper Road, City O',
    price: '$92',
    location: 'City O',
    size: 'Small',
    rooms: 9,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (15).webp'),
    type: 'Apartment',
  },
  {
    id: 16,
    title: '963 Magnolia Street, City P',
    price: '$110',
    location: 'City P',
    size: 'Large',
    rooms: 15,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (6).webp'),
    type: 'Apartment',
  },
  {
    id: 17,
    title: '258 Pineapple Lane, City Q',
    price: '$88',
    location: 'City Q',
    size: 'Medium',
    rooms: 11,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (7).webp'),
    type: 'Apartment',
  },
  {
    id: 18,
    title: '753 Cherry Street, City R',
    price: '$130',
    location: 'City R',
    size: 'Small',
    rooms: 7,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (3).webp'),
    type: 'Apartment',
  },
  {
    id: 19,
    title: '369 Apple Court, City S',
    price: '$98',
    location: 'City S',
    size: 'Large',
    rooms: 18,
    availability: 'sold',
    imageUrl: require('../../images/apartment-properties (1).webp'),
    type: 'Apartment',
  },
  {
    id: 20,
    title: '852 Banana Avenue, City T',
    price: '$115',
    location: 'City T',
    size: 'Medium',
    rooms: 13,
    availability: 'available',
    imageUrl: require('../../images/apartment-properties (8).webp'),
     type: 'Apartment',
  },
];
