export const studioData = [
    {
      id: 1,
      title: 'Modern Studio Apartment',
      price: '$800/month',
      location: 'City Center',
      size: 'Small',
      rooms: 1,
      availability: 'available',
      imageUrl: require('../../images/studio-properties (1).webp'),
      type: 'Studio',
    },
    {
      id: 2,
      title: 'Cozy Studio Loft',
      price: '$700/month',
      location: 'Urban Area',
      size: 'Medium',
      rooms: 1,
      availability: 'available',
      imageUrl: require('../../images/studio-properties (2).webp'),
      type: 'Studio',
    },
    {
      id: 3,
      title: 'Bright Studio Space',
      price: '$900/month',
      location: 'Artsy District',
      size: 'Small',
      rooms: 1,
      availability: 'available',
      imageUrl: require('../../images/studio-properties (3)'),
      type: 'Studio',
    },
    {
      id: 4,
      title: 'Luxury Studio Retreat',
      price: '$1,000/month',
      location: 'Exclusive Neighborhood',
      size: 'Medium',
      rooms: 1,
      availability: 'available',
      imageUrl: require('../../images/studio-properties (4)'),
      type: 'Studio',
    },
  ];
  