export const townhomeData = [
    {
      id: 1,
      title: 'Modern Townhome',
      price: '$450,000',
      location: 'Suburban Community',
      size: 'Medium',
      rooms: 3,
      availability: 'available',
      imageUrl: require('../../images/town-home (1).webp'),
      type: 'Townhome',
    },
    {
      id: 2,
      title: 'Luxury Townhome with Garden',
      price: '$600,000',
      location: 'Upscale Neighborhood',
      size: 'Large',
      rooms: 4,
      availability: 'available',
      imageUrl: require('../../images/town-home (2).webp'),
      type: 'Townhome',
    },
    {
      id: 3,
      title: 'Cozy Townhome Retreat',
      price: '$380,000',
      location: 'Quiet Suburb',
      size: 'Small',
      rooms: 2,
      availability: 'available',
      imageUrl: require('../../images/town-home (3).webp'),
      type: 'Townhome',
    },
    {
      id: 4,
      title: 'Spacious Townhome with Rooftop',
      price: '$700,000',
      location: 'City Center',
      size: 'Large',
      rooms: 5,
      availability: 'available',
      imageUrl: require('../../images/town-home (4).webp'),
      type: 'Townhome',
    },
    {
        id: 5,
        title: 'Modern Townhome',
        price: '$450,000',
        location: 'Suburban Community',
        size: 'Medium',
        rooms: 3,
        availability: 'available',
        imageUrl: require('../../images/town-home (5).webp'),
        type: 'Townhome',
      },
      {
        id: 6,
        title: 'Luxury Townhome with Garden',
        price: '$600,000',
        location: 'Upscale Neighborhood',
        size: 'Large',
        rooms: 4,
        availability: 'available',
        imageUrl: require('../../images/town-home (6).webp'),
        type: 'Townhome',
      },
      {
        id: 7,
        title: 'Cozy Townhome Retreat',
        price: '$380,000',
        location: 'Quiet Suburb',
        size: 'Small',
        rooms: 2,
        availability: 'available',
        imageUrl: require('../../images/town-home (7).webp'),
        type: 'Townhome',
      },
      {
        id: 8,
        title: 'Spacious Townhome with Rooftop',
        price: '$700,000',
        location: 'City Center',
        size: 'Large',
        rooms: 5,
        availability: 'available',
        imageUrl: require('../../images/town-home (8).webp'),
        type: 'Townhome',
      },
      {
        id: 9,
        title: 'Luxury Townhome with Garden',
        price: '$600,000',
        location: 'Upscale Neighborhood',
        size: 'Large',
        rooms: 4,
        availability: 'available',
        imageUrl: require('../../images/town-home (9).webp'),
        type: 'Townhome',
      },
      {
        id: 10,
        title: 'Cozy Townhome Retreat',
        price: '$380,000',
        location: 'Quiet Suburb',
        size: 'Small',
        rooms: 2,
        availability: 'available',
        imageUrl: require('../../images/town-home (10).webp'),
        type: 'Townhome',
      },
      {
        id: 11,
        title: 'Spacious Townhome with Rooftop',
        price: '$700,000',
        location: 'City Center',
        size: 'Large',
        rooms: 5,
        availability: 'available',
        imageUrl: require('../../images/town-home (11).webp'),
        type: 'Townhome',
      },
  ];
  